=== 表示

==== 文字化け

* 文字化けが発生していないこと

==== 表示桁数、表示方法、フォーマット

[horizontal]
日時::
+
--
日時に関して期待した通り表示されていること。以下は例

* 2018/04/30 01:23:45
* 2018/4/30 1:23:45 (0を表示しないケース)
* 2018年04年30日 01時23分45秒
* 2018-04-30 01:23:45
* 20180430012345 (区切りなしケース)
* 4/30/2018, 1:23 p.m. (英語表記)
* Apr. 30, 2018 , at 1:23 p.m. (英語表記2)
--
+
郵便番号::
+
--
郵便番号に関して期待した通り表示されていること。以下は例

* 〒012-3456
* 012-3456 (記号なし)
* 0123456 (ハイフンなし)
--
+
電話番号::
+
--
電話番号に関して期待した通り表示されていること。以下は例

* 090-1234-5678
* 09012345678 (ハイフンなし)
* 012-345-6789 (市外/内局番の考慮)
--
+
金額::
+
--
金額に関して期待した通り表示されていること。以下は例

* ￥1,000-
* 1000 (記号やカンマなし)
--
+
負数::
+
--
負数に関して期待した通り表示されていること。以下は例

* -1,000
* 1,000 (赤字表示)
--

==== テーブル表示

[horizontal]
項目(カラム)(列):: テーブル項目に不足がないこと
件数(行):: 期待した件数だけ表示されていること
0件:: テーブルの表示件数が0件の場合は期待した通り表示されていること

==== ページング

===== ページング不可(0件の場合)

* ページング対象の一覧の表示件数が0件の場合は期待した通り表示されていること

===== ページング不可(1Pのみの場合)

[horizontal]
範囲:: ページングができない場合(1ページのみの場合など)はページャーの番号が期待した通り表示されること
前へボタン:: ページングができない場合(1ページのみの場合など)は前へボタンが期待した通り表示されること
次へボタン:: ページングができない場合(1ページのみの場合など)は次へボタンが期待した通り表示されること

===== ページング可(複数ページの場合) / 最小値(1～10Pであれば1P)

[horizontal]
範囲:: ページングができる、かつ中間値が選択されている場合にはページャーの番号が期待した通り表示されること
前へボタン:: ページングができる、かつ中間値が選択されている場合には前へボタンが期待した通り表示されること
次へボタン:: ページングができる、かつ中間値が選択されている場合には次へボタンが期待した通り表示されること

===== ページング可(複数ページの場合) / 中間値(1～10Pであれば5P)

[horizontal]
範囲:: ページングができる、かつ最小値が選択されている場合にはページャーの番号が期待した通り表示されること
前へボタン:: ページングができる、かつ最小値が選択されている場合には前へボタンが期待した通り表示されること
次へボタン:: ページングができる、かつ最小値が選択されている場合には次へボタンが期待した通り表示されること

===== ページング可(複数ページの場合) / 最大値(1～10Pであれば10P)

[horizontal]
範囲:: ページングができる、かつ最大値が選択されている場合にはページャーの番号が期待した通り表示されること
前へボタン:: ページングができる、かつ最大値が選択されている場合には前へボタンが期待した通り表示されること
次へボタン:: ページングができる、かつ最大値が選択されている場合には次へボタンが期待した通り表示されること

==== ソート

[horizontal]
昇順:: 昇順にソートされること
降順:: 降順にソートされること

==== フォーム要素

===== デフォルト表示

[horizontal]
テキストボックス::
+
--
テキストボックスに期待したデフォルト値が表示されていること。以下は例

* 登録時 : 空欄
* 更新時 : 現在の登録されている値
--
+
テキストエリア::
+
--
テキストエリアに期待したデフォルト値が表示されていること。以下は例

* 登録時 : 空欄
* 更新時 : 現在の登録されている値
--
+
チェックボックス::
+
--
チェックボックスに期待したデフォルト値が設定されること。以下は例

* 登録時 : 未選択
* 更新時 : 現在の登録されている値
--
+
ラジオボタン::
+
--
ラジオボタンに期待したデフォルト値が設定されること。以下は例

* 登録時 : 未選択
* 更新時 : 現在の登録されている値
--
+
セレクトボックス(ドロップボックス)::
+
--
セレクトボックス(ドロップボックス)に期待したデフォルト値が設定されること。以下は例

* 登録時 : 未選択
* 更新時 : 現在の登録されている値
--

===== プレースホルダ

* テキストボックスのプレースホルダが期待した通り表示されていること

===== セレクトボックスの内容

* セレクトボックスの一覧が期待した通り表示されていること

===== 制御

[horizontal]
入力値の保持:: 各種入力欄に入力し次画面へ進んだのち、試験該当画面へ戻った場合には入力した値が保持されていること
ロール/権限::
+
--
ロールや権限に応じてフォームが表示されていること

* 一般ユーザーの場合は特定のボタンが表示されていないこと
* 管理者の場合は特定のボタンが表示されていること
--

==== 帳票

[horizontal]
レイアウト:: 帳票のレイアウトに関して期待した通り表示されていること

==== ウィンドウ

[horizontal]
ページタイトル:: ウィンドウのページタイトルが期待した通り表示されていること
favicon:: ウィンドウのfaviconが期待した通り表示されていること

==== Copyright(コピーライト)

* Copyright(コピーライト)が期待した通り表示されていること

==== 処理(ボタン押下後など)

[horizontal]
画面遷移:: 期待通りの画面遷移が行われること
画面更新::
+
--
処理に伴う画面更新において、更新後の各種内容が期待した通りに表示されていること。以下は例

* 登録後に登録したデータが一覧に存在する
* 更新後の該当項目が変更されている
* 削除後は一覧に該当データが存在しない
--
+
メッセージ:: 処理結果に対するメッセージが期待した通り表示されていること

==== 画面制御

[horizontal]
ポップアップウィンドウ:: 期待した通りポップアップウィンドウが表示され、また内容が期待した通りの内容であること
モーダルウィンドウ:: 期待した通りモーダルウィンドウが表示され、また内容が期待した通りの内容であること
タブオーダー:: タブまたはEnterキーでの項目遷移が期待した通り行われること

==== レスポンシブ

[horizontal]
PC(大) (1200px以上):: 1200px以上のサイズにて検証を行い画面崩れがないこと
PC (992~1119px):: 992~1119pxのサイズにて検証を行い画面崩れがないこと
タブレット (768~991px):: 768~991pxのサイズにて検証を行い画面崩れがないこと
スマートフォン (767以下):: 767px以下のサイズにて検証を行い画面崩れがないこと
画面サイズ変更:: 画面サイズを変更しても画面崩れがないこと

NOTE: 境界値は bootstrap の値を参照

==== 推奨ブラウザ

===== バージョン

[horizontal]
最新:: 指定されたバージョン内で最も新しいバージョンにて検証を行い画面崩れがないこと
最古:: 指定されたバージョン内で最も古いバージョンにて検証を行い画面崩れがないこと

===== ブラウザ

[horizontal]
google chrome:: google chromeで検証を行い画面崩れがないこと
fire fox:: fire foxで検証を行い画面崩れがないこと
ie:: internet explorerで検証を行い画面崩れがないこと
edge:: edgeで検証を行い画面崩れがないこと
safari:: safariで検証を行い画面崩れがないこと
opera:: operaで検証を行い画面崩れがないこと

==== セキュリティ

[horizontal]
エスケープ処理::
+
--
入力値を表示するさいなどにはエスケープ処理が施されて表示されていること。以下は例

* 入力画面にて入力欄に `<script>alert('danger')</script>` など入力したうえで確認画面へ遷移してもアラートが表示されないこと
--
