=== 入力

==== 入力チェック

[horizontal]
必須:: 必須項目が未入力の場合はエラーとなること
最小値(または桁数や文字数)::
+
--
下記の観点より期待した通り処理されること

* 未満
* 同値
* 超過
--
+
最大値(または桁数や文字数)::
+
--
下記の観点より期待した通り処理されること

* 未満
* 同値
* 超過
--
+
指定値(画像認証など):: 入力値が期待値以外の場合はエラーとなること
メールアドレス:: フォーマットに違反している場合はエラーとなること
URL:: フォーマットに違反している場合はエラーとなること
電話番号(固定電話、携帯電話など):: フォーマットに違反している場合はエラーとなること
郵便番号(3桁-4桁など):: フォーマットに違反している場合はエラーとなること
日時:: フォーマットに違反している場合はエラーとなること
存在しない日時:: 存在しない日時を入力した場合はエラーとなること
うるう年:: うるう年を入力した場合は期待した通り処理されること
期間外の日時:: 期間外の日時を入力した場合はエラーとなること
日時の前後関係:: 開始日時と終了日時が逆転している場合はエラーとなること
クレジットカード:: フォーマットに違反している場合はエラーとなること
ファイル指定:: 指定外のファイルをアップロードした場合はエラーとなること
ファイルサイズ:: ファイルサイズの指定を超過したファイルをアップロードした場合はエラーとなること

==== 文字チェック

[horizontal]
全角(カナ、英数字、記号含む):: 禁止されている場合はエラーとなること (`ヲンヰヱヴーヾ・`)
半角(記号):: 禁止されている場合はエラーとなること (`,'" ./\=?!:;`)
半角(カタカナ):: 禁止されている場合はエラーとなること (`ｧｰｭｿﾏﾞﾟ`)
環境依存文字:: 禁止されている場合はエラーとなること (`㌶Ⅲ⑳㏾☎㈱髙﨑`)
UTF-8とEUCでマッピングに差がある文字:: 禁止されている場合はエラーとなること (`¢£¬‖−〜―`)
サロゲートペア:: 禁止されている場合はエラーとなること (`𠀋𡈽𡌛𡑮𡢽𠮟𡚴𡸴𣇄𣗄`)
絵文字:: 禁止されている場合はエラーとなること (`😀🐱🚗`)
EUCのサーバで文字化けする文字:: 禁止されている場合はエラーとなること (`ソ能表`)
javascript:: 入力欄へjavascriptの入力が禁止されている場合はエラーとなること (`<script>alert('danger')</script>`)
HTML:: 入力欄へHTMLの入力が禁止されている場合はエラーとなること (`<font color="red">`)
HTML特殊文字:: 入力欄へHTML特殊文字の入力が禁止されている場合はエラーとなること (`&lt;&copy;&amp;`)
データベースに対するインジェクション:: 入力欄へSQLの入力が禁止されている場合はエラーとなること (`';delete from user_table;`)
改行:: 禁止されている場合はエラーとなること
空白文字(半角、全角):: 禁止されている場合はエラーとなること
NULL(空、未入力):: 禁止されている場合はエラーとなること

==== 入力パターン

[horizontal]
小数:: 小数を入力し期待した通り処理されること
負数:: 負数を入力し期待した通り処理されること
検索条件/前方一致:: 対象の有無に応じて期待した通り処理されること
検索条件/後方一致:: 対象の有無に応じて期待した通り処理されること
検索条件/部分一致:: 対象の有無に応じて期待した通り処理されること
検索条件/完全一致:: 対象の有無に応じて期待した通り処理されること
検索条件/期間指定:: 対象の有無に応じて期待した通り処理されること。また時刻に関しては時分秒まで考慮すること
検索条件/検索条件の組み合わせ:: 複数の検索条件を組み合わせることができる場合には組み合わせたパターンを作成し、それぞれのパターンで期待した通り処理されること

==== フォーム要素の制御

[horizontal]
ボタン押下によるリクエスト二重送信:: 確定ボタン押下後は二度押しができない、もしくは二度目がエラーとなること
パスワード入力欄:: パスワード入力欄の入力値は隠ぺいされて表示されること
セレクトボックス::
+
--
下記の観点より期待した通り処理されること

* 単一選択
* 複数選択
--
+
チェックボックス::
+
--
下記の観点より期待した通り処理されること

* 単一選択
* 複数選択

全選択が可能な場合はシナリオを考慮し期待した通り処理されること。以下は例

* A->B->C->全解除->全選択->B解除
--
+
フォーム要素の有効化:: 特定の条件を満たすことで有効となる要素がある場合には、条件を満たしたタイミングで要素が有効化されること
フォーム要素の無効化:: 条件を満たすことで有効化した要素がある場合には、条件を満たしていない状態とすることで無効化されること

==== ブラウザ操作

[horizontal]
ブラウザバック後の再送信:: 確定ボタン押下後の完了画面などにてブラウザバックし、再度確定ボタン押下した場合に再度リクエストが送信されないこと
マルチウィンドウ(タブ)からの送信:: 画面Aで確定ボタン押下直前まで処理を進め、その後画面Bを開き画面Aと同様の処理を進めて確定ボタン押下。その後、画面Aの確定ボタンを押下した場合にはリクエストが送信されないこと
リロードによる再リクエスト送信:: 処理完了後にリロードした場合に再度リクエストが送信されないこと
未ログイン状態によるアクセス:: 未ログイン状態にてURL指定でアクセスした場合はエラーとなること
不正遷移:: 登録->確認->完了といった画面遷移が必要な場合に、完了画面のURL指定でアクセスした場合はエラーとなること
ディレクトリトラバーサル:: `../` などのURL指定でアクセスした場合にはエラーとなること
