=== リクエスト

[NOTE]
====
基本的にはクライアント/入力の観点と同様
====

==== 入力チェック(CSV/TSV ファイル)

CSV ファイルや TSV ファイルなどのチェック観点。

[horizontal]
項目(カラム)数境界::
+
--
下記の観点より期待した通り処理されること

* 未満
* 超過
--
+
項目(カラム)の桁数(文字数)境界 / 最小値(桁数)::
+
--
下記の観点より期待した通り処理されること

* 未満
* 同値
* 超過
--
+
項目(カラム)の桁数(文字数)境界 / 最大値(桁数)::
+
--
下記の観点より期待した通り処理されること

* 未満
* 同値
* 超過
--
+
Key(Unique)項目の重複:: Keyとなる項目値が重複している場合はエラーとなること
データ件数(レコード数)境界値 / 最小数::
+
--
下記の観点より期待した通り処理されること

* 未満
* 同値
* 超過
--
+
データ件数(レコード数)境界値 / 最大数::
+
--
下記の観点より期待した通り処理されること

* 未満
* 同値
* 超過
--
+
ヘッダの有無:: ヘッダがない場合はエラーとなること
トレーラ(フッタ)の有無:: トレーラがない場合はエラーとなること
ヘッダ/データ/トレーラ(フッタ)の順序:: ヘッダ/データ/トレーラの順序がバラバラの場合はエラーとなること
空行:: 空行がある場合はエラーとなること
デリミタの有無:: デリミタ(区切り文字)がない場合はエラーとなること
空ファイル:: 空ファイルの場合はエラーとなること
指定文字(prefixなど)の有無:: 値に指定文字(prefixなど)がない場合はエラーとなること
ダブルクォーテーション:: ダブルクォーテーションの有無で期待した通り処理されること
ダブルクォーテーション内の改行:: ダブルクォーテーション内の改行の有無で期待した通り処理されること

==== 入力チェック(固定長ファイル(マルチフォーマット))

[horizontal]
レコード長境界値::
+
--
下記の観点より期待した通り処理されること

* 未満
* 超過
--

[NOTE]
====
上記以外は CSV/TSV のチェックと同様
====
