name: asciidoc to html

on:
  # main ブランチを push された場合にトリガ
  # (期待としては、プルリクがマージされた場合のみ動かしたい)
  push:
    branches: [ main ]

  # Actions タブからこのワークフローを実行することを許可する(?)
  workflow_dispatch:

jobs:
  asciidoc-to-html:
    runs-on: ubuntu-latest

    steps:
      # チェックアウト ($GITHUB_WORKSPACE でディレクトリへアクセスできる)
      - name: checkout
        uses: actions/checkout@v2

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: install asciidoctor
        run: gem install asciidoctor

      # docs ディレクトリに adoc ファイルから html ファイルを生成
      - run: asciidoctor -D $GITHUB_WORKSPACE/docs -o index.html $GITHUB_WORKSPACE/src/main.adoc
      - run: asciidoctor -D $GITHUB_WORKSPACE/docs -o ubuntu.html $GITHUB_WORKSPACE/src/ubuntu/main.adoc
      - run: asciidoctor -D $GITHUB_WORKSPACE/docs -o python.html $GITHUB_WORKSPACE/src/python/main.adoc
      - run: asciidoctor -D $GITHUB_WORKSPACE/docs -o php.html $GITHUB_WORKSPACE/src/php/main.adoc
      - run: asciidoctor -D $GITHUB_WORKSPACE/docs -o asciidoc-cheatsheet.html $GITHUB_WORKSPACE/src/asciidoc-cheatsheet/asciidoc-cheatsheet.adoc
      - run: asciidoctor -D $GITHUB_WORKSPACE/docs -o unittest-cheatsheet.html $GITHUB_WORKSPACE/src/unittest-cheatsheet/main.adoc
      - run: asciidoctor -D $GITHUB_WORKSPACE/docs -o 5w2h.html $GITHUB_WORKSPACE/src/5w2h/5w2h.adoc

      - name: switch public branch
        run: |
          git fetch origin public
          git switch public

      - name: commit and push
        run: |
          git config user.name yoshik159753-ci
          git config user.email kai.outsider.777+github.ci@gmail.com
          git add .
          git commit -m "Add generated HTML files"
          git push origin public
